language:
  ruby

rvm:
  - "2.0.0"

env:
  - DB=sqlite DEVISE_SECRET_KEY=1111122222333334444455555abcdefgjklopqt

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake routes
  - bundle exec rake
  - rails -v

bundler_args: --binstubs=./bundler_stubs
